name: Build & Release

# When a commit is tagged with a version tag.
on:
  push:
    branches: 
      - main
#     tags:
#       - v*


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: PyInstaller Prep
        run: |
          mv cater.spec cater/
          mv requirements.txt cater/
      - name: PyInstaller Windows
        uses: JackMcKew/pyinstaller-action-windows@v0.1.2
        with:
          path: cater
      - name: Review Files
          run: ls -Rhlst
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: Cater.exe
      #     path: ./
