name: Build & Release

# When a commit is tagged with a version tag.
on:
  push:
    branches: 
      - main
#     tags:
#       - v*


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Testing
        run: |
          pip install pyinstaller
          pyinstaller_loc=$(whereis pyinstaller | grep -w /)
          cd $pyinstaller_loc
          ls -Rhlst
#       - name: PyInstaller Prep
#         run: |
#           mv cater.spec cater/
#           mv requirements.txt cater/
#       - name: PyInstaller Windows
#         uses: JackMcKew/pyinstaller-action-windows@v0.1.2
#         with:
#           path: cater
#       - name: PyInstaller Linux
#         uses: JackMcKew/pyinstaller-action-linux@0.1.4
#         with:
#           path: cater
#       - name: Review contents
#         run: ls -Rhlst
#       - name: Move Executables
#         run: |
#           mv ./cater/dist/windows/__main__.exe Cater.exe
#           mv ./cater/dist/linux/__main__ Cater
#       - uses: actions/upload-artifact@v2
#         with:
#           name: Cater - Windows
#           path: ./Cater.exe
#       - uses: actions/upload-artifact@v2
#         with:
#           name: Cater - Linux
#           path: ./Cater
